### ISSUE TITLE
410 'gone' error while creating an issue

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/javascript-fetch-lab#142]
I was on a screen share with a student who was getting 410 'gone' error while creating an issue on the forked repo. Whenever he made the request it gave an error `index.js:20 POST https://api.github.com/repos/Enoch2k2/javascript-fetch-lab/issues 410 (Gone)`.

He said he copied and pasted the solution to try to get it to work and it still gave the same error. He also went to his settings and enabled issues on his repo. I also cloned my version to see (out of a hunch that maybe the api updated). And I had gotten the same issue. If you clone the solution from learn-co-students and attempt to make that fetch. You may also get the same error. Hence I believe this lab may need to be re-worked to keep up with the github api unless the error is something totally different then what i suspect it to be.

**Comment by gj** [comment]
Hi @Enoch2k2 !

Make sure you have enabled issues on the repository you're trying to create them on. The one you linked, `https://api.github.com/repos/Enoch2k2/javascript-fetch-lab`, currently does not have them enabled:
```json
{
  "id": 100745128,
  "name": "javascript-fetch-lab",
  "full_name": "Enoch2k2/javascript-fetch-lab",
  ...
  "has_issues": false,
  ...
}
```

I'd point the student at the relevant bit in the [instructions](https://github.com/learn-co-curriculum/javascript-fetch-lab#instructions):
>3. Navigate to your forked repository (using the link in your html!) and **enable Issues by clicking on the Settings tab and checking Issues. They will probably be turned off by default, and the next step won't work so well if they are disabled!**

Let me know if that doesn't fix it for you! 🙂
