### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by zoebisch** [learn-co-curriculum/javascript-fetch-lab#164]
issues!

**Comment by zoebisch** [comment]
What the heck? I am scratching my head on this one...

**Comment by sgharms** [comment]
I was a bit baffled too, but hope all is well otherwise :)

**Comment by zoebisch** [comment]
I am wondering is somehow something got crossed, there was the github api lab...but I have no clue how this happened. I certainly wouldn’t have done it intentionally!
